dist: trusty
sudo: required
language: python
python:
  - "3.6"
addons:
  sonarcloud:
    organization: "aarontraas-github"
    token:
      secure:
install:
  - python setup.py install
  - sonar-scanner
